### ISSUE TITLE
Last commits of PHPDocBlock-lite broke spore

### ISSUE THREAD

**Issue by mathielen** [dannykopping/spore#22]
Hi,

The commits from Jun 07 at PHPDocBlock-lite broke the spore library. It doesnt work anymore. Says something with property 'name' doesnt exist anymore in MethodElement. At least in AutoRouter.php are multiple locations where method->name is used.
I downgraded PHPDocBlock-lite to 0.3. Now it works again.

Could you please fix that?

Thanks
Markus

**Comment by dannykopping** [comment]
Hey @mathielen 
Sorry mate - I was going to get around to this tonight.

I'm in the process of porting Spore over to Laravel, since that it what I'm using mostly at work now.

Check it out:
https://github.com/dannykopping/spore-l4

Still early days, but it'll have most of the same functionality within the next couple weeks.

**Comment by mathielen** [comment]
Cool stuff! I will check on this.
Actually right now i'm using spore in a medium large project and i'm pretty happy with it. Thanks again.

**Comment by dannykopping** [comment]
That's really exciting! I'll let you know once the Spore integration into
Laravel is production-ready; I'll be testing it out on a fairly big
back-office system I'm building so it'll be fairly solid and tested by the
time I release it into the wild.
